# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Mark's Nook
tagline:          'A personal blog about technology, IT and open source.'
description:      'Musings about Rust, TypeScript, WebAssembly, DevOps, software in general, open source, system design and curious problems others might find useful.'
url:              https://lazycat.hu
baseurl:          /

author:
  name:           'Mark Tolmacs'
  url:            https://marktolmacs.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mtolmacs/mtolmacs.github.io

plugins:          [jekyll-gist,jekyll-paginate]

excerpt_separator: <!--more-->